### PR TITLE
Merge UIMA 3.1.1 release branch

### PR DESCRIPTION
**Pull request by reckart**
Merge the branch on which  UIMA Java SDK 3.1.1 was released to update the version in the POMs on the master branch and to incorporate any changes that were done as part of the UIMA Java SDK 3.1.1 release.

### CODE REVIEW

**Comment by reckart** [comment]
@mischor Looks like we didn't merge the RC branch into master after the 3.1.1 release. I think we should do this. The master branch still lists as being 3.1.1-SNAPSHOT instead of 3.1.2-SNAPSHOT as it should. After merging the RC branch into master, we should delete it. I have update this branch with the latest changes from master and resolved conflicts so we can easily merge it back - just wanted to check back with you that you don't have any objections against the suggested procedure.

**Comment by mischor** [comment]
Sorry to be a bit slow these days, due to other things... Let me think about this a bit, please...

**Comment by mischor** [comment]
Yes, this looks like an oversight... I'll do the merge now

**Comment by mischor** [comment]
Merged, and branch deleted...

**Pull request merged**
