### PR TITLE
[UIMA-6274] Setting feature on builtin JCas cover class that was loaded before initializing TypeSystemImpl fails

### PR DESCRIPTION
**Pull request by reckart**
- Introduce TypeSystemImpl.createCallSiteForBuiltIn() to provide special handling for the static TSI initialization being triggered by loading a built-in JCas cover class.
- Updated the built-in JCas cover classes to use the new method to initialize their feature callsites
- Added unit test
- Fixed typo in comment

### CODE REVIEW

**Comment by reckart** [comment]
@mischor this might be one you'd care to have a quick look at.

**Comment by reckart** [comment]
@mischor instead of introducing another `createCallsiteForBuiltins` method, I was considering to add a check into the exiting `createCallsite` which would check if the given JCas cover class is a built-in and then perform the extra logic - or even to perform the extra logic in any case, even for non-built-in classes.

**Comment by SergeAverbis** [comment]
This correction solve the problem in my environment.

**Comment by reckart** [comment]
Given no additional feedback was submitted, I am assuming this is alright and merge it.

**Pull request merged**
