### PR TITLE
[UIMA-6136] fix hashcode and equals for FsIndexComparatorImpl

### PR DESCRIPTION
**Pull request by mischor**
please see if this fixes the performance issue

### CODE REVIEW

**Comment by mischor** [comment]
Were you able to test this? If so, did it fix the performance issue?

**Comment by reckart** [comment]
I'm about to check :)

**Comment by reckart** [comment]
Looks good!

**Comment by reckart** [comment]
Would it be sensible to suggest introducing an interface for key specs (i.e. a super-interface for Feature and LinearTypeOrder) which would provide special methods for hashcode and comparison using non-default names?

**Comment by mischor** [comment]
Maybe.  I usually try and trade off doing that (which to me is a bit of an "indirection") against the principle of don't repeat yourself.  In particular, if this kind of test/measurement was needed in more that one place, then it would make sense, but if it's only used once, then the indirection makes the code slightly harder to follow, when you're reading it later.

**Pull request merged**
