### PR TITLE
[UIMA-6200] Constructing aggregate engines is slow

### PR DESCRIPTION
**Pull request by reckart**
- Added a couple of different approaches and some unit tests
- This remains work in progress

**Jira issue:** https://issues.apache.org/jira/browse/UIMA-6200

### CODE REVIEW

**Comment by mischor** [comment]
@reckart I reviewed this and I agree with your choices :-).  Let's convert the default flow descriptor to the new "make" method.  Do you want to do the cleanup of this PR?  If not, let me know, and I'll do it :-)

**Comment by reckart** [comment]
I can do the clean up and then ping you again for approval.

**Comment by reckart** [comment]
@mischor ping

**Comment by mischor** [comment]
Hi, thanks for also fixing the capability language flow.  I noticed you deleted the xml's for these in the Resources (and then added them under the test/resources); that could break user code, in case any user made use of these.  Can you undo this part of the change?

**Comment by reckart** [comment]
I could - but in fact, the whole change could break user code if the user for some reason relies on overriding the XML files with own custom templates. The question is: how high is the risk of this breaking user code?

**Comment by mischor** [comment]
You make an interesting point, one that I had not ever thought of.  The use case imagines that a user changes / overrides the resource in the uimaj-core jar that defines this.  In terms of categorizing this kind of thing, I guess I would put it on a par (or maybe slightly below) with a user changing /overriding any other artifact in uima-core.jar.  

I think this might fall into the category of "you're-on-your-own" if you go and change/override uimaj jar artifacts that aren't specifically documented to be overridable.

Also, if a user wanted a different flow controller, they would I think naturally write their own custom flow controller spec, rather than override a default.  

So my guess is that this kind of overriding of the default flow controller xml's is probably not being done.  

I do think that we try to "promise" our users that we won't change artifacts they might depend on, without a lot of documentation, etc., around those changes, so users can be pretty comfortable if they are using UIMA in a "normal" manner that minor updates won't break things.   
I guess I feel that the default flow controller specs in the uimaj-core resources falls into this category, and things will be (slightly) more stable if those are not moved with this change.

**Comment by reckart** [comment]
@mischor good for merging now?

**Comment by reckart** [comment]
@mischor ping?

**Comment by mischor** [comment]
ping ack.  I'll try to get to this today...

**Comment by mischor** [comment]
two small things:  1) The FixedFlowController.java file has a now unused private method loadDefaultDescription.  I guess this should be removed or commented out if we want to preserve it in the record for future reference.
2) The deprecation comments in the resources/ ... xml files have a misspelling:
    In future versions of UIMA, this fill will be removed entirely.
    In future versions of UIMA, this file will be removed entirely.

If you want to fix them, please do, otherwise, I'll just merge as is... :-)

**Comment by reckart** [comment]
Will fix and merge afterwards. I'd remove the method.

So after merging this into v2, I can merge v2 into v3 or I can merge just this PR into v3. As often mentioned before, I usually I merge the entire maintenance branch. I just wanted to check with you if you have meanwhile formed an opinion or if it is fine for me to proceed as usual.

**Comment by mischor** [comment]
I don't know.  I have the feeling that doing this might mess up the branch.  But if you're pretty confident it would work, please give it a try, after confirming it is only changing what it ought to :-)  Otherwise, I'm happy to manually copy the update...

**Pull request merged**
