### PR TITLE
[UIMA-6168] protect indexes fails when there were no indexed fs that needed protecting

### PR DESCRIPTION
**Pull request by reckart**
- Restore dropping protection levels in the CAS when closing a FSsTobeAddedback context

@mischor Unfortunately, I can't provide a unit test because I only have a hunch in which situation this happens exactly. The piece of code I encountered problems in is pretty complex and a unit test is not easy to extract. Maybe you have a good idea for constructing a proper unit test once you see this fix.

**Jira link:** https://issues.apache.org/jira/browse/UIMA-6168

### CODE REVIEW

**Comment by mischor** [comment]
posted a long analysis in the Jira, this fix needs a couple of modifications.

**Comment by reckart** [comment]
@mischor It looks like this fix should not be needed for UIMAv3 - is that correct?

**Comment by reckart** [comment]
@mischor Hm, looks like the initial UIMA-6168 changes went into UIMAv3, so probably this fix should also be merged to UIMAv3.

**Comment by mischor** [comment]
Confirming, this fix needs to go into v3.

**Pull request merged**
