### PR TITLE
[UIMA-6126] Add .gitignore file to trunk

### PR DESCRIPTION
**Pull request by reckart**
- Ignore files that should not go into the repo

https://issues.apache.org/jira/browse/UIMA-6126

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by mischor** [comment]
I noticed this change was for trunk, which has been now renamed to master.  The "trunk" branch will be deleted, as soon as INFRA changes the default to "master".  Can you update this or redo it to go against "master" branch?

**Comment by mischor** [comment]
Other gitignore candidates include: api-change-report and issuesFixed.

**Comment by reckart** [comment]
The target branch can be changed via the "Edit" button on the top of the PR. I'll change it.

**Pull request merged**
